import { resolve } from 'node:path';
import type { ArchitecturePlan, ProvenanceRecord } from '../types.js';
import { writeFileEnsured, projectRoot, todayIso } from '../util/io.js';
import { capabilityName } from '../capability/taxonomy.js';
import { mayCopyCode } from '../license/gate.js';

/**
 * Plugin Builder.
 *
 * Emits a real Claude Code plugin directory from an ArchitecturePlan. The
 * layout follows the documented plugin structure: `.claude-plugin/plugin.json`,
 * `skills/<name>/SKILL.md`, `agents/<name>.md`, `hooks/hooks.json`.
 *
 * v0.1 policy, enforced here in code: no third-party source is copied. Every
 * generated file is written by this builder from the analysis result, so the
 * PROVENANCE "Reused Code" column is None by construction, not by promise.
 */

export interface BuildResult {
  outputDir: string;
  files: string[];
  provenance: ProvenanceRecord[];
  /** Capabilities that were selected but which the plugin can only advise on. */
  advisoryOnly: string[];
}

export interface BuildOptions {
  outputRoot?: string;
  researchDate?: string;
}

export function buildPlugin(plan: ArchitecturePlan, opts: BuildOptions = {}): BuildResult {
  const root = opts.outputRoot ?? resolve(projectRoot(), 'generated', 'plugins');
  const outputDir = resolve(root, plan.pluginName);
  const files: string[] = [];
  const researchDate = opts.researchDate ?? todayIso();

  const write = (relative: string, contents: string) => {
    writeFileEnsured(resolve(outputDir, relative), contents.endsWith('\n') ? contents : contents + '\n');
    files.push(relative);
  };

  const wantedSkills = componentNames(plan, 'skill');
  const wantedAgents = componentNames(plan, 'agent');

  write('.claude-plugin/plugin.json', renderManifest(plan));
  write('capability-manifest.json', renderCapabilityManifest(plan, researchDate));
  write('config/default.json', renderDefaultConfig(plan));
  write('README.md', renderPluginReadme(plan));

  for (const skill of wantedSkills) write(`skills/${skill}/SKILL.md`, renderSkill(skill, plan));
  for (const agent of wantedAgents) write(`agents/${agent}.md`, renderAgent(agent, plan));

  // A hook is only emitted when the architecture actually asked for one.
  if (componentNames(plan, 'hook').length > 0) {
    write('hooks/hooks.json', renderHooks(plan));
  }

  const provenance = buildProvenance(plan, researchDate);
  write('PROVENANCE.md', renderProvenanceMarkdown(plan, provenance, researchDate));

  const advisoryOnly = plan.stack.entries
    .filter((e) => !mayCopyCode(e.capability.licenseStatus))
    .map((e) => e.capabilityId);

  return { outputDir, files, provenance, advisoryOnly };
}

/** The plugin's own component index, so the router can hand off by name. */
function componentIndex(plan: ArchitecturePlan): string {
  const lines: string[] = [];
  for (const name of componentNames(plan, 'skill')) {
    lines.push(`- \`skills/${name}/SKILL.md\` — ${skillDescription(name, plan)}`);
  }
  for (const name of componentNames(plan, 'agent')) {
    lines.push(`- \`agents/${name}.md\` — subagent for ${name.replace(/-agent$/, '')} work.`);
  }
  lines.push('- `config/default.json` — the single configuration surface every capability reads.');
  lines.push('- `capability-manifest.json` — what this plugin can do and how well each claim is evidenced.');
  return lines.join('\n');
}

function componentNames(plan: ArchitecturePlan, kind: string): string[] {
  const names = new Set<string>();
  for (const layer of plan.layers) {
    for (const c of layer.components) {
      if (c.kind === kind) names.add(c.name);
    }
  }
  // Original-layer components are skills unless they are already a component.
  if (kind === 'skill') {
    for (const oc of plan.originalComponents) names.add(oc.id);
  }
  return [...names].filter((n) => /^[a-z0-9-]+$/.test(n));
}

function renderManifest(plan: ArchitecturePlan): string {
  const manifest: Record<string, unknown> = {
    name: plan.pluginName,
    displayName: plan.displayName,
    version: '0.1.0',
    description: plan.description,
    keywords: [...new Set(plan.stack.entries.map((e) => e.capabilityId))],
  };
  if (componentNames(plan, 'agent').length > 0) manifest.agents = ['./agents/'];
  if (componentNames(plan, 'hook').length > 0) manifest.hooks = './hooks/hooks.json';
  manifest.userConfig = Object.fromEntries(
    Object.entries(plan.unifiedConfig).map(([key, v]) => [
      key,
      { type: v.type.replace('[]', ''), title: key, description: v.description },
    ]),
  );
  return JSON.stringify(manifest, null, 2);
}

function renderCapabilityManifest(plan: ArchitecturePlan, researchDate: string): string {
  return JSON.stringify(
    {
      $comment:
        'Machine-readable record of what this plugin can do and how well each claim is evidenced. Generated by oss-integrate; do not hand-edit.',
      plugin: plan.pluginName,
      generatedOn: researchDate,
      goal: plan.stack.goal.goal,
      capabilities: plan.stack.entries.map((e) => ({
        capabilityId: e.capabilityId,
        name: e.capability.name,
        category: e.capability.category,
        origin: e.origin,
        inspiredBy: e.capability.sourceRepository,
        selectionAxis: e.selectionAxis,
        evidence: e.capability.evidence.class,
        confidence: e.capability.confidence,
        licenseStatus: e.capability.licenseStatus,
        securityStatus: e.capability.securityStatus,
        reusedCode: 'none',
        limitations: e.capability.limitations,
      })),
      originalComponents: plan.originalComponents.map((o) => ({ id: o.id, rationale: o.rationale })),
      unresolvedConflicts: plan.conflicts.filter((c) => !c.resolved).map((c) => c.subject),
      unknown: plan.stack.decisions.filter((d) => d.decision === 'UNKNOWN').map((d) => d.capabilityId),
    },
    null,
    2,
  );
}

function renderDefaultConfig(plan: ArchitecturePlan): string {
  const out: Record<string, unknown> = {};
  for (const [key, v] of Object.entries(plan.unifiedConfig)) {
    out[key] = v.default ?? null;
  }
  return JSON.stringify(out, null, 2);
}

function renderSkill(name: string, plan: ArchitecturePlan): string {
  const body = SKILL_BODIES[name]?.(plan) ?? genericSkillBody(name, plan);
  return `---
name: ${name}
description: ${skillDescription(name, plan)}
---

${body}`;
}

const skillDescription = (name: string, plan: ArchitecturePlan): string => {
  const caps = plan.stack.entries.map((e) => e.capabilityId).join(', ');
  switch (name) {
    case 'capability-router':
      return `Route a request for ${plan.stack.goal.goal} to the right capability in this plugin, in the right order. Use when the user asks for work covering any of: ${caps}.`;
    case 'build-surface':
      return 'Produce or modify the web artifact this plugin is about, applying the design and implementation capabilities in the stack.';
    case 'verification-runner':
      return 'Run the verification capabilities against a URL and return measured results rather than impressions.';
    case 'evidence-ledger':
      return 'Record what was measured versus assumed for each capability result, and refuse to report an unmeasured claim as a fact.';
    case 'namespace-guard':
      return 'Own the single public command surface of this plugin so colliding names from the source projects are not re-emitted.';
    case 'unlock-advisor':
      return 'Report which one or two missing capabilities would unlock a larger capability for this stack.';
    default:
      return `${name} capability of ${plan.pluginName}.`;
  }
};

const SKILL_BODIES: Record<string, (plan: ArchitecturePlan) => string> = {
  'capability-router': (plan) => {
    const steps = plan.workflow.map((w) => `- ${w}`).join('\n');
    const caps = plan.stack.entries
      .map(
        (e) =>
          `| ${e.capabilityId} | ${e.capability.evidence.class} | ${e.capability.confidence} | ${e.capability.sourceRepository} |`,
      )
      .join('\n');
    return `# Capability Router

This plugin was assembled for one goal:

> ${plan.stack.goal.goal}

It carries exactly the capabilities that goal needs. Anything outside this
table was deliberately left out.

| Capability | Evidence | Confidence | Concept source |
| --- | --- | --- | --- |
${caps}

## Order of work

${steps}

Run prerequisites before dependants. If a prerequisite is unavailable, say so
and stop - do not substitute a weaker check and present it as the same result.

## Routing rules

1. A request to create or change the artifact goes to the Build layer first.
2. Never report the artifact as finished before the Verify layer has run.
3. Every claim you make about the artifact must name what produced it. If
   nothing produced it, mark it UNKNOWN rather than filling the gap.
4. When a capability the request needs is not in the table above, say it is
   not in this plugin. Do not improvise it.

## Components in this plugin

Hand off to these rather than doing their work here. Nothing else exists: if a
request needs something not listed, say so.

${componentIndex(plan)}

## Configuration

Defaults live in \`config/default.json\`. Read that file before running any
capability, and treat a value the user has overridden as authoritative.

${Object.entries(plan.unifiedConfig)
  .map(([k, v]) => `- \`${k}\` (${v.type}): ${v.description}`)
  .join('\n')}
`;
  },

  'verification-runner': (plan) => {
    const verify = plan.layers.find((l) => l.name === 'Verify');
    const caps = (verify?.capabilities ?? []).map((c) => `- **${capabilityName(c)}** (\`${c}\`)`).join('\n');
    const entries = plan.stack.entries.filter((e) => (verify?.capabilities ?? []).includes(e.capabilityId));
    const notes = entries
      .map(
        (e) =>
          `- \`${e.capabilityId}\`: concept from ${e.capability.sourceRepository} (${e.capability.licenseStatus}). ${
            mayCopyCode(e.capability.licenseStatus)
              ? 'Reuse of its code is permitted under its licence conditions, but this plugin does not vendor it - invoke the upstream tool instead.'
              : 'Its code is NOT reusable here; invoke the upstream tool as an external process, or implement the check independently.'
          }`,
      )
      .join('\n');
    return `# Verification Runner

Turns claims about the page into measured facts.

## Capabilities in scope

${caps || '- (none selected)'}

## Procedure

1. Read \`baseUrl\` and \`viewports\` from \`config/default.json\`, applying any
   user override. If \`baseUrl\` is not set, stop and ask for it. Do not guess
   a URL.
2. For each viewport, drive the browser to the page and collect the raw
   artifacts the selected capabilities need.
3. Run each capability's check and record its numeric or boolean result.
4. Hand every result to \`evidence-ledger\` before reporting it.
5. Report failures at or above the configured \`failOn\` severity as blocking.

## Source posture

${notes || '- (none)'}

## What this skill must never do

- Report a check as passing when it did not run. An unrun check is UNKNOWN.
- Average, round, or soften a measured number to make output look better.
- Substitute a screenshot for an accessibility or performance measurement.
`;
  },

  'evidence-ledger': (plan) => {
    const rows = plan.stack.entries
      .map(
        (e) =>
          `| ${e.capabilityId} | ${e.capability.evidence.class} | ${e.capability.securityStatus} | ${e.capability.licenseStatus} |`,
      )
      .join('\n');
    return `# Evidence Ledger

Every result this plugin reports carries an evidence class. This skill assigns
it and refuses to let a weaker one be presented as a stronger one.

## Classes

| Class | Means |
| --- | --- |
| VERIFIED | An executable check ran in this session and passed. |
| SUPPORTED | Source, a reproducible example, or official documentation backs it. |
| INFERRED | Derived from indirect signal. |
| CLAIMED | Only a README or a tool's own description says so. |
| UNKNOWN | Not established. Say UNKNOWN; do not fill it in. |

## Capability posture inherited from the build

| Capability | Evidence at selection | Security gate | Licence posture |
| --- | --- | --- | --- |
${rows}

## Rules

1. A capability that did not run this session cannot report VERIFIED.
2. A capability whose security gate is not PASS must have that stated in the
   output whenever its result is used.
3. Never present a REFERENCE_ONLY capability as if this plugin contains the
   upstream implementation. It contains an independent implementation of the
   idea, or a call out to the upstream tool.
4. Contradiction between two capabilities is reported, not reconciled.
`;
  },

  'namespace-guard': (plan) => {
    const collisions = plan.conflicts
      .map((c) => `- \`${c.subject}\` (${c.kind}) from ${c.parties.join(', ')} - ${c.resolution}`)
      .join('\n');
    return `# Namespace Guard

The source projects this plugin draws from collided on names the host resolves
globally. This plugin exposes each of those once, owned here.

## Resolved collisions

${collisions || '- (none detected)'}

## Rules

1. Do not re-expose a source project's original command, hook, or agent name.
2. A new public name must not shadow one already listed above.
3. If a collision cannot be resolved by naming, report it instead of silently
   letting the host pick a winner.
`;
  },

  'unlock-advisor': (plan) => {
    const oc = plan.originalComponents.find((o) => o.id === 'unlock-advisor');
    const lines = (oc?.justifiedBy ?? []).map((j) => `- ${j}`).join('\n');
    return `# Unlock Advisor

This stack is one or two capabilities short of a larger capability. Say so
plainly rather than shipping the weaker workflow as if it were complete.

## Near misses recorded at build time

${lines || '- (none)'}

## Rules

1. Report the specific missing capability, not a vague suggestion to "add more
   tooling".
2. Do not claim the unlocked capability is available. It is not, until the
   missing piece is added.
`;
  },

  'build-surface': (plan) => {
    const build = plan.layers.find((l) => l.name === 'Build');
    const caps = (build?.capabilities ?? []).map((c) => `- **${capabilityName(c)}** (\`${c}\`)`).join('\n');
    return `# Build Surface

Produces and modifies the artifact this plugin is about.

## Capabilities in scope

${caps || '- (none selected)'}

## Procedure

1. Establish what is being built and against which viewports (see
   \`viewports\` in the plugin configuration).
2. Make the change.
3. Hand off to the Verify layer. This skill does not judge its own output -
   that separation is why the plugin exists.

## Rules

- Do not declare the work finished. Only the Verify layer can do that.
- Record any decision you made that the goal did not specify, so it can be
  challenged rather than inherited silently.
`;
  },
};

function genericSkillBody(name: string, plan: ArchitecturePlan): string {
  const oc = plan.originalComponents.find((o) => o.id === name);
  return `# ${name}

${oc?.rationale ?? `Component of ${plan.pluginName}.`}

## Justified by

${(oc?.justifiedBy ?? []).map((j) => `- ${j}`).join('\n') || '- (not recorded)'}
`;
}

function renderAgent(name: string, plan: ArchitecturePlan): string {
  const verify = plan.layers.find((l) => l.name === 'Verify');
  const judge = plan.layers.find((l) => l.name === 'Judge');
  const isVerification = name === 'verification-agent';
  const caps = (isVerification ? verify?.capabilities : judge?.capabilities) ?? [];
  const description = isVerification
    ? `Run this plugin's verification capabilities against a URL and return measured results. Use when a page must be checked, not described.`
    : `Review measured verification output against the goal and report concrete defects with the evidence for each.`;

  return `---
name: ${name}
description: ${description}
tools: [Read, Bash, Glob, Grep]
---

# ${isVerification ? 'Verification Agent' : 'Review Agent'}

Goal this plugin serves:

> ${plan.stack.goal.goal}

## Capabilities you own

${caps.map((c) => `- **${capabilityName(c)}** (\`${c}\`)`).join('\n') || '- (none)'}

## How you work

${
  isVerification
    ? `1. Confirm \`baseUrl\` is configured. If not, stop and ask.
2. Run each capability above and capture its raw output.
3. Report a table of capability, result, and the artifact that proves it.
4. Any capability that could not run is reported as UNKNOWN with the reason.`
    : `1. Read the verification output. Do not re-run the checks.
2. For each defect, cite the measurement that shows it.
3. Rank by severity, not by how easy the fix is.
4. If the verification output is missing a capability, say the review is
   incomplete rather than inferring the result.`
}

## Hard rules

- Never report a result you did not observe.
- Never soften a measured failure into a suggestion.
- "Looks fine" is not a finding. Cite a number or an artifact, or say UNKNOWN.
`;
}

function renderHooks(plan: ArchitecturePlan): string {
  return JSON.stringify(
    {
      $comment: `Generated for ${plan.pluginName}. Only hooks the architecture asked for are emitted.`,
      hooks: {},
    },
    null,
    2,
  );
}

export function buildProvenance(plan: ArchitecturePlan, researchDate: string): ProvenanceRecord[] {
  const records: ProvenanceRecord[] = [];

  for (const entry of plan.stack.entries) {
    const cap = entry.capability;
    const decision = plan.stack.decisions.find(
      (d) => d.capabilityId === entry.capabilityId && d.candidate === cap.sourceRepository,
    );
    const component =
      plan.layers.find((l) => l.capabilities.includes(entry.capabilityId))?.components.map((c) => c.name).join(', ') ??
      'capability-router';
    records.push({
      source: cap.sourceRepository.startsWith('fixture-') ? 'local fixture' : 'public GitHub repository',
      repository: cap.sourceRepository,
      author: cap.sourceRepository.split('/')[0] ?? 'UNKNOWN',
      license: cap.licenseStatus,
      commitOrRelease: cap.sourceVersion,
      researchDate,
      capability: entry.capabilityId,
      adoptedConcept: cap.description,
      reusedCode: 'None',
      modification:
        'Not applicable - no upstream code was copied, so there is nothing modified. The capability was re-specified for this plugin.',
      originalContribution: `Independent specification of ${entry.capabilityId} inside the ${plan.pluginName} architecture, with an evidence class attached to every result.`,
      evidence: cap.evidence.class,
      decision: decision?.decision ?? 'KEEP',
      generatedComponent: component,
    });
  }

  for (const oc of plan.originalComponents) {
    records.push({
      source: 'original',
      repository: '(none)',
      author: 'this project',
      license: 'MIT (this project)',
      commitOrRelease: 'UNKNOWN',
      researchDate,
      capability: oc.id,
      adoptedConcept: '(none - designed for this stack)',
      reusedCode: 'None',
      modification: 'Not applicable.',
      originalContribution: oc.rationale,
      evidence: 'SUPPORTED',
      decision: 'ADD',
      generatedComponent: `skills/${oc.id}/SKILL.md`,
    });
  }

  return records;
}

function renderProvenanceMarkdown(
  plan: ArchitecturePlan,
  records: ProvenanceRecord[],
  researchDate: string,
): string {
  const rows = records
    .map(
      (r) =>
        `| ${r.capability} | ${r.repository} | ${r.author} | ${r.license} | ${r.commitOrRelease} | ${r.evidence} | ${r.decision} | ${r.reusedCode} | ${r.generatedComponent} |`,
    )
    .join('\n');

  const details = records
    .map(
      (r) => `### ${r.capability} — ${r.repository}

- **Source**: ${r.source}
- **Research date**: ${r.researchDate}
- **Adopted concept**: ${r.adoptedConcept}
- **Reused code**: ${r.reusedCode}
- **Modification**: ${r.modification}
- **Original contribution**: ${r.originalContribution}
- **Evidence**: ${r.evidence}
- **Decision**: ${r.decision}
`,
    )
    .join('\n');

  return `# PROVENANCE — ${plan.pluginName}

Generated ${researchDate} by \`oss-integrate build\`.

**Reused code: None.** This plugin contains no third-party source. Every file
was generated from the analysis result. Where a capability was inspired by an
upstream project, that project is credited below as a *concept* source, and the
plugin either invokes the upstream tool as an external process or implements
the idea independently.

## Summary

| Capability | Repository | Author | Licence posture | Version | Evidence | Decision | Reused code | Generated component |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
${rows}

## Detail

${details}
`;
}

function renderPluginReadme(plan: ArchitecturePlan): string {
  const caps = plan.stack.entries
    .map((e) => `- **${e.capability.name}** (\`${e.capabilityId}\`) — evidence ${e.capability.evidence.class}, concept from ${e.capability.sourceRepository}`)
    .join('\n');
  const unresolved = plan.conflicts.filter((c) => !c.resolved);
  const unknown = plan.stack.decisions.filter((d) => d.decision === 'UNKNOWN');

  return `# ${plan.displayName}

${plan.description}

Generated by \`oss-integrate build\`. Do not hand-edit: rerun the build instead,
so the provenance and the code stay in sync.

## Capabilities

${caps || '- (none selected)'}

## Architecture

${plan.layers.map((l) => `### ${l.name}\n\n${l.responsibility}\n\nCapabilities: ${l.capabilities.join(', ') || '(orchestration only)'}`).join('\n\n')}

## Workflow

${plan.workflow.map((w) => `- ${w}`).join('\n')}

## Configuration

${Object.entries(plan.unifiedConfig).map(([k, v]) => `- \`${k}\` (${v.type}) — ${v.description}`).join('\n')}

## Known limitations

${
  unresolved.length > 0
    ? unresolved.map((c) => `- Unresolved ${c.kind} on \`${c.subject}\`: ${c.resolution}`).join('\n')
    : '- No unresolved conflicts were detected at build time.'
}
${
  unknown.length > 0
    ? '\n' + unknown.map((d) => `- \`${d.capabilityId}\`: UNKNOWN — ${d.reason}`).join('\n')
    : ''
}

## Provenance

See [PROVENANCE.md](./PROVENANCE.md). Reused third-party code: **None**.
`;
}
